---
stages:
  - validate-syntax
  - test-unit
  - acceptance-puppet4
  - acceptance-puppet5

before_script:
  - pdk --version

pdk_validate:
  stage: 'validate-syntax'
  script:
    - pdk validate
  tags:
    - puppet-tests

pdk_test_unit:
  stage: 'test-unit'
  script:
    - pdk test unit
  tags:
    - puppet-tests

acceptance_with_puppet4_ubuntu:
  stage: 'acceptance-puppet4'
  variables:
    BEAKER_PUPPET_COLLECTION: 'pc1'
  script:
    - pdk bundle exec rake beaker:default
  tags:
    - puppet-tests
  except:
    - master

acceptance_with_puppet4_debian:
  stage: 'acceptance-puppet4'
  variables:
    BEAKER_PUPPET_COLLECTION: 'pc1'
  script:
    - pdk bundle exec rake beaker:debian-82-x64
  tags:
    - puppet-tests
  except:
    - master

acceptance_with_puppet4_centos:
  stage: 'acceptance-puppet4'
  variables:
    BEAKER_PUPPET_COLLECTION: 'pc1'
  script:
    - pdk bundle exec rake beaker:centos-72-x64
  tags:
    - puppet-tests
  except:
    - master

acceptance_with_puppet5_ubuntu:
  stage: 'acceptance-puppet5'
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet5'
  script:
          - pdk bundle exec rake beaker:default
  tags:
    - puppet-tests
  except:
    - master

acceptance_with_puppet5_debian:
  stage: 'acceptance-puppet5'
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet5'
  script:
    - pdk bundle exec rake beaker:debian-82-x64
  tags:
    - puppet-tests
  except:
    - master

acceptance_with_puppet5_centos:
  stage: 'acceptance-puppet5'
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet5'
  script:
    - pdk bundle exec rake beaker:centos-72-x64
  tags:
    - puppet-tests
  except:
    - master

