.rubocop.yml:
  selected_profile: off

.travis.yml:
  delete: true

Gemfile:
  required:
    ':development':
      - gem: 'beaker-rspec'
      - gem: 'beaker-puppet'
      - gem: 'beaker-vagrant'
      - gem: 'beaker-puppet_install_helper'
      - gem: 'beaker-module_install_helper'
