.rubocop.yml:
  selected_profile: off

Gemfile:
  required:
    ':development':
      - gem: 'beaker-rspec'
      - gem: 'beaker-puppet_install_helper'
      - gem: 'beaker-module_install_helper'
      - gem: 'nokogiri'
        version: '= 1.8.2'
